details:
  namespace: student90-bookinfo-uat
  image: ghcr.io/sathipp/bookinfo-details
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.uat.opsta.net
  path: "/student90/details(/|$)(.*)"
  serviceType: ClusterIP